name: Air Quality Model Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write  # Required to push outputs back to repo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run model script
        run: python models.py

      - name: List output files
        run: ls -R outputs/

      - name: Commit output folder to repository
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add outputs/
          git commit -m "Add outputs from model run" || echo "No changes to commit"
          git push

      - name: Upload outputs as GitHub Action artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: model-outputs
          path: outputs/
